<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => './assets/front/js/app.js',
        'entrypoint' => true,
    ],
    'admin' => [
        'path' => './assets/admin/js/admin.js',
        'entrypoint' => true,
    ],
    'admin-form' => [
        'path' => './assets/admin/js/admin-form.js',
        'entrypoint' => true,
    ],
    '@hotwired/stimulus' => [
        'version' => '3.2.2',
    ],
    'tom-select' => [
        'version' => '2.3.1',
    ],
    '@tarekraafat/autocomplete.js' => [
        'version' => '10.2.7',
    ],
];
