; ---------------------------
; OPcache - ENV local
; ---------------------------
opcache.enable=1
opcache.enable_cli=0

; Build every changed file
opcache.validate_timestamps=1
opcache.revalidate_freq=0

; Set Up Memory
opcache.memory_consumption=128
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000

; Prevents aggressive optimizations
opcache.optimization_level=-1

; Disable preload (useless in dev)
opcache.preload=
opcache.preload_user=

; Quick invalidation file
opcache.file_update_protection=0

; Logs
opcache.log_verbosity_level=3