services:
  php:
    image: gibass/php:8.4
    container_name: ${PROJECT_NAME}-php
    environment:
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      SCRIPTS_DIR: ${SCRIPTS_DIR:-}
      APP_DIR: ${APP_DIR:-/var/www/html}
      DEV_UID: ${UID}
      ENV: ${ENV:-}
    volumes:
      - ${WORKSPACE}:/var/www/html
    networks:
      - internal

  nginx:
    image: nginx:stable
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${WORKSPACE}/docker/nginx/conf/conf.d:/etc/nginx/conf.d:ro
      - ${WORKSPACE}/docker/nginx/conf/certs:/etc/nginx/certs
      - ${WORKSPACE}/public:/var/www/html/public
    networks:
      - internal

  database:
    image: mysql:8.4
    container_name: ${PROJECT_NAME}-database
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "6033:3306"
    volumes:
      - ${WORKSPACE}/docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - internal

networks:
  internal:
    driver: bridge
